name: srcsep
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - pytorch-cuda=11.8
  - python=3.9
  - pip:
    - matplotlib
    - obspy
    - pandas
    - numpy
    - scipy
    - gitpython
    - h5py
    - seaborn
    - pathlib
    - packaging
    - termcolor
